# Generated by Django 2.1.8 on 2019-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person1',
            name='Contact',
            field=models.IntegerField(default='0', max_length=30),
        ),
    ]
